# Site settings
author: Amber
title: Scraping
header-img: img/home-bg.png
email: ambzzzz@gmail.com
copyright_name: Amber
description: > # this means to ignore newlines until "baseurl:"
  When you're scraping for a good deal
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Amberganda

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
